"""Fix relationship in the data models

Revision ID: 6895b4f23022
Revises: 4bad40c6462f
Create Date: 2025-01-23 13:24:38.116610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6895b4f23022'
down_revision: Union[str, None] = '4bad40c6462f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('plan_cnt', sa.Integer(), nullable=True))
    op.add_column('user_profile', sa.Column('plan_comp_cnt', sa.Integer(), nullable=True))
    op.add_column('user_profile', sa.Column('plan_ip_cnt', sa.Integer(), nullable=True))
    op.add_column('user_profile', sa.Column('goals', sa.Text(), nullable=True))
    op.add_column('user_profile', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('user_profile', sa.Column('sex', sa.String(length=1), nullable=True))
    op.add_column('user_profile', sa.Column('logon_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_profile', sa.Column('role', sa.String(length=50), nullable=True))
    op.add_column('user_profile', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user_profile', sa.Column('is_instructor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'is_instructor')
    op.drop_column('user_profile', 'is_admin')
    op.drop_column('user_profile', 'role')
    op.drop_column('user_profile', 'logon_time')
    op.drop_column('user_profile', 'sex')
    op.drop_column('user_profile', 'gender')
    op.drop_column('user_profile', 'goals')
    op.drop_column('user_profile', 'plan_ip_cnt')
    op.drop_column('user_profile', 'plan_comp_cnt')
    op.drop_column('user_profile', 'plan_cnt')
    # ### end Alembic commands ###
