"""Added Post Types & Interactions

Revision ID: d078bf445cda
Revises: 20710f46598b
Create Date: 2025-01-24 17:06:25.136084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.datamodels.datamodels import Base
target_metadata = Base.metadata

# revision identifiers, used by Alembic.
revision: str = 'd078bf445cda'
down_revision: Union[str, None] = '20710f46598b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('subtitle', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('post_type_id', sa.Integer(), nullable=True))
    op.execute("INSERT INTO post_types (id, name) VALUES (1, 'thoughts')")
    op.add_column('posts', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('custom_subcategory', sa.String(), nullable=True))
    op.create_foreign_key(None, 'posts', 'post_types', ['post_type_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'subcategories', ['subcategory_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'])
    op.execute("UPDATE posts SET post_type_id = 1")
    op.alter_column('posts', 'post_type_id', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'custom_subcategory')
    op.drop_column('posts', 'subcategory_id')
    op.drop_column('posts', 'category_id')
    op.drop_column('posts', 'post_type_id')
    op.drop_column('posts', 'subtitle')
    # ### end Alembic commands ###
